"""Evidence report generator.

Design rule for this project's documentation: prose is written by hand, numbers
are generated. `docs/*.md` explain what the system does and why; every measured
figure lives in `docs/generated/EVIDENCE.md`, rendered from the metadata
ledgers by this module.

That split is what makes "do not claim a metric you have not reproduced"
enforceable rather than aspirational: if a table below says NOT MEASURED, the
run that would have produced it has not happened.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Sequence

from taxi.metadata.store import MetadataStore

NOT_MEASURED = "_Not measured yet. Run the command shown above._"


def markdown_table(rows: Sequence[dict[str, Any]], columns: Sequence[str] | None = None) -> str:
    if not rows:
        return NOT_MEASURED
    columns = list(columns or rows[0].keys())
    header = "| " + " | ".join(columns) + " |"
    divider = "| " + " | ".join("---" for _ in columns) + " |"
    body = [
        "| " + " | ".join(_cell(row.get(column)) for column in columns) + " |"
        for row in rows
    ]
    return "\n".join([header, divider, *body])


def _cell(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:,.4f}".rstrip("0").rstrip(".") if abs(value) < 1e6 else f"{value:,.2f}"
    if isinstance(value, int):
        return f"{value:,}"
    return str(value).replace("|", "\\|")


class EvidenceReport:
    def __init__(self, settings, store: MetadataStore | None = None):
        self.settings = settings
        self.store = store or MetadataStore(settings)

    def _safe(self, sql: str) -> list[dict[str, Any]]:
        try:
            return self.store.query(sql)
        except Exception:  # noqa: BLE001 - a missing ledger is a legitimate state
            return []

    def render(self) -> str:
        sections: list[Callable[[], str]] = [
            self._header,
            self._environment,
            self._sources,
            self._reconciliation,
            self._rejections,
            self._determinism,
            self._marts,
            self._benchmarks,
            self._ml,
            self._ml_segments,
            self._footer,
        ]
        return "\n\n".join(section() for section in sections) + "\n"

    def write(self, path: Path | None = None) -> Path:
        target = Path(path or self.settings.paths.docs_generated / "EVIDENCE.md")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(self.render(), encoding="utf-8")
        return target

    # -- sections --------------------------------------------------------------
    def _header(self) -> str:
        return (
            "# Measured Evidence\n\n"
            "Generated by `taxi report`. Every number here was produced by a run "
            "recorded in `data/metadata/`; nothing in this file is hand-written.\n\n"
            f"_Generated {datetime.now():%Y-%m-%d %H:%M:%S}._"
        )

    def _environment(self) -> str:
        rows = self._safe(
            """
            SELECT duckdb_version, python_version, host, code_version,
                   contract_fingerprint, max(start_time) AS latest_run, count(*) AS runs
            FROM pipeline_runs
            GROUP BY 1,2,3,4,5 ORDER BY latest_run DESC LIMIT 5
            """
        )
        return "## Environment\n\n`taxi status`\n\n" + markdown_table(rows)

    def _sources(self) -> str:
        rows = self._safe(
            """
            SELECT * EXCLUDE (__rn) FROM (
              SELECT year, month, source_location, file_size_bytes, row_count,
                     ingestion_status, schema_status, substr(file_hash, 1, 12) AS file_hash,
                     row_number() OVER (PARTITION BY source_id
                       ORDER BY coalesce(ingestion_time, acquisition_time) DESC) AS __rn
              FROM source_manifest
            ) WHERE __rn = 1 ORDER BY year, month
            """
        )
        totals = self._safe(
            """
            SELECT count(*) AS source_files, sum(row_count) AS raw_rows,
                   sum(file_size_bytes) AS raw_bytes
            FROM (
              SELECT * EXCLUDE (__rn) FROM (
                SELECT row_count, file_size_bytes,
                       row_number() OVER (PARTITION BY source_id
                         ORDER BY coalesce(ingestion_time, acquisition_time) DESC) AS __rn
                FROM source_manifest) WHERE __rn = 1)
            """
        )
        return (
            "## Source manifest\n\n`taxi acquire` / `taxi manifest --show`\n\n"
            + markdown_table(totals)
            + "\n\n"
            + markdown_table(rows)
        )

    def _reconciliation(self) -> str:
        rows = self._safe(
            """
            SELECT * EXCLUDE (__rn) FROM (
              SELECT year, month, raw_rows, clean_rows, rejected_rows,
                     round(rejection_rate * 100, 3) AS rejection_rate_pct,
                     top_rejection_reason, reconciliation_passed,
                     row_number() OVER (PARTITION BY year, month
                       ORDER BY checked_at DESC) AS __rn
              FROM reconciliation
            ) WHERE __rn = 1 ORDER BY year, month
            """
        )
        totals = self._safe(
            """
            SELECT sum(raw_rows) AS raw_rows, sum(clean_rows) AS clean_rows,
                   sum(rejected_rows) AS rejected_rows,
                   bool_and(reconciliation_passed) AS all_reconciled
            FROM (
              SELECT * EXCLUDE (__rn) FROM (
                SELECT raw_rows, clean_rows, rejected_rows, reconciliation_passed,
                       row_number() OVER (PARTITION BY year, month
                         ORDER BY checked_at DESC) AS __rn
                FROM reconciliation) WHERE __rn = 1)
            """
        )
        return (
            "## Clean / rejected reconciliation\n\n"
            "Invariant: `raw_rows = clean_rows + rejected_rows` for every partition.\n\n"
            + markdown_table(totals) + "\n\n" + markdown_table(rows)
        )

    def _rejections(self) -> str:
        rows = self._aggregate_reason_counts()
        return (
            "## Rejection reasons\n\n"
            "Counts every reason a row broke, so they sum to at least the rejected "
            "row count. `mart_anomalies` carries the same figures split by month "
            "and by primary reason.\n\n" + markdown_table(rows)
        )

    def _aggregate_reason_counts(self) -> list[dict[str, Any]]:
        """Fallback that parses the JSON reason counts in Python."""
        import json

        rows = self._safe("SELECT reason_counts_json FROM reconciliation")
        totals: dict[str, int] = {}
        for row in rows:
            try:
                for reason, count in json.loads(row["reason_counts_json"] or "{}").items():
                    totals[reason] = totals.get(reason, 0) + int(count)
            except (ValueError, TypeError):
                continue
        return [
            {"reason": reason, "rows_flagged": count}
            for reason, count in sorted(totals.items(), key=lambda kv: -kv[1])
        ]

    def _determinism(self) -> str:
        rows = self._safe(
            """
            SELECT year, month, layer, rows_before, rows_after,
                   content_identical, bytes_identical, round(duration_seconds, 2) AS seconds
            FROM backfill_runs ORDER BY executed_at DESC, year, month, layer LIMIT 40
            """
        )
        return (
            "## Backfill determinism\n\n`taxi backfill --from ... --to ...`\n\n"
            "`content_identical` compares order-independent row-set fingerprints; "
            "`bytes_identical` is reported but never asserted (it is a property of "
            "the Parquet writer, not of the pipeline).\n\n" + markdown_table(rows)
        )

    def _marts(self) -> str:
        rows = self._safe(
            """
            SELECT mart, count(*) AS partitions, sum(rows_written) AS rows,
                   round(sum(duration_seconds), 2) AS total_seconds,
                   max(built_at) AS last_built
            FROM mart_builds WHERE status = 'BUILT'
            GROUP BY 1 ORDER BY 1
            """
        )
        return "## Marts built\n\n`taxi marts build`\n\n" + markdown_table(rows)

    def _benchmarks(self) -> str:
        rows = self._safe(
            """
            WITH latest AS (
              SELECT *, row_number() OVER (
                  PARTITION BY query_name, source_type ORDER BY measured_at DESC) AS __rn
              FROM benchmarks
            ),
            pivoted AS (
              SELECT query_name,
                     max(CASE WHEN source_type = 'clean_layer'
                              THEN runtime_seconds_median END) AS clean_layer_seconds,
                     max(CASE WHEN source_type = 'mart'
                              THEN runtime_seconds_median END) AS mart_seconds,
                     any_value(result_fingerprint)             AS correctness_check
              FROM latest WHERE __rn = 1 GROUP BY 1
            )
            SELECT query_name, clean_layer_seconds, mart_seconds,
                   round(clean_layer_seconds / nullif(mart_seconds, 0), 2) AS speedup_x,
                   correctness_check
            FROM pivoted ORDER BY speedup_x DESC NULLS LAST
            """
        )
        return (
            "## Query performance: clean layer vs mart\n\n`taxi bench run`\n\n"
            "Both variants answer the same question over the same data; the "
            "correctness column is the row-by-row comparison of their results.\n\n"
            + markdown_table(rows)
        )

    def _ml(self) -> str:
        rows = self._safe(
            """
            SELECT model, variant, split, train_period, validation_period, test_period,
                   n_train, n_eval, round(mae, 4) AS mae, round(rmse, 4) AS rmse,
                   round(r2, 4) AS r2
            FROM ml_evaluations
            WHERE evaluated_at = (SELECT max(evaluated_at) FROM ml_evaluations)
            ORDER BY variant, split, mae
            """
        )
        return (
            "## Model comparison (temporal split)\n\n`taxi ml train`\n\n"
            "Baselines are included because a model that cannot beat a grouped "
            "median is not worth deploying.\n\n" + markdown_table(rows)
        )

    def _ml_segments(self) -> str:
        rows = self._safe(
            """
            SELECT model, variant, segment_kind, segment_value, n,
                   round(mae, 3) AS mae, round(bias, 3) AS bias
            FROM ml_segment_errors
            WHERE split = 'test'
              AND evaluated_at = (SELECT max(evaluated_at) FROM ml_segment_errors)
            ORDER BY mae DESC LIMIT 20
            """
        )
        return (
            "## Where the model fails (worst test segments)\n\n"
            "Positive bias = the model over-predicts that segment.\n\n"
            + markdown_table(rows)
        )

    def _footer(self) -> str:
        return (
            "---\n\n"
            "Ledgers behind this report: `data/metadata/*.parquet` (with `.csv` "
            "mirrors). Each row carries the `run_id` that produced it."
        )
